name: Escaneo de Gitleaks en cada push

on:
  push:
    branches: [ master]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Escaneo con Gitleaks
        uses: zricethezav/gitleaks-action@v2.3.3
