name: Escaneo de Gitleaks en cada push

on:
  push:
    branches: [ master]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Ejecutar Gitleaks
        run: |
          gitleaks detect --source=. --verbose --exit-code 1
